export enum OperationCode {
  STACK_PUSH_STRING,
  STACK_PUSH_DWORD,
  STACK_PUSH_BOOLEAN,
  STACK_PUSH_NULL,
  STACK_PUSH_UNDEFINED,
  STACK_PUSH_DUPLICATE,
  STACK_POP,

  ARITHMETIC_ADD,
  ARITHMETIC_SUB,
  ARITHMETIC_MUL,
  ARITHMETIC_DIV,
  ARITHMETIC_MOD,

  COMPARISON_EQUAL,
  COMPARISON_STRICT_EQUAL,
  COMPARISON_NOT_EQUAL,
  COMPARISON_STRICT_NOT_EQUAL,
  COMPARISON_LESS,
  COMPARISON_LESS_OR_EQUAL,
  COMPARISON_GREATER,
  COMPARISON_GREATER_OR_EQUAL,

  BINARY_BIT_SHIFT_LEFT,
  BINARY_BIT_SHIFT_RIGHT,
  BINARY_UNSIGNED_BIT_SHIFT_RIGHT,
  BINARY_BIT_XOR,
  BINARY_BIT_AND, 
  BINARY_BIT_OR,

  UNARY_PLUS,
  UNARY_MINUS,
  UNARY_NOT,
  UNARY_BIT_NOT,
  UNARY_TYPEOF,

  LOAD_VARIABLE,
  STORE_VARIABLE,

  LOAD_GLOBAL,

  CALL_FUNCTION,
  CALL_METHOD,
  CONSTRUCT,

  GET_PROPERTY,
  SET_PROPERTY,

  BUILD_ARRAY,
  BUILD_OBJECT,
  BUILD_FUNCTION,

  JUMP,
  JUMP_IF_TRUE,
  JUMP_IF_FALSE,

  RETURN,
  DEBUGGER,
};